name: CI Weekly Code Check

on:
        push:
                branches: [master]
        schedule:
                - cron: '0 0 * * 0'

jobs:
        Check-code:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v3
                        - run: docker build . --tag ninjaninja140/test:test
